twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null

    form_themes:
        - "form/fields.html.twig"
    globals:
        site_name: "%site_name%"
        main_color: "%main_color%"
        project_name: "%project_name%"
        project_url: "%project_url%"
        project_url_display: "%project_url_display%"
        helloasso_registration_campaign_url: "%helloasso_registration_campaign_url%"
        due_duration_by_cycle: '%due_duration_by_cycle%'
        support_email: '%transactional_mailer_user%'
        images_tmp_dir: '%images_tmp_dir%'
        shift_service: '@App\Service\ShiftService'
        maximum_nb_of_beneficiaries_in_membership: '%maximum_nb_of_beneficiaries_in_membership%'
        unlimited_book_duration: '%unlimited_book_duration%'
        allow_extra_shifts: '%allow_extra_shifts%'
        max_time_in_advance_to_book_extra_shifts: '%max_time_in_advance_to_book_extra_shifts%'
        code_generation_enabled: '%code_generation_enabled%'
        local_currency_name: '%local_currency_name%'