<?php

namespace AppBundle\Repository;

/**
 * CodeBoxAccessForShifterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CodeBoxAccessForShifterRepository extends \Doctrine\ORM\EntityRepository
{
}
