<?php

namespace AppBundle\Repository;

/**
 * CodeBoxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CodeBoxRepository extends \Doctrine\ORM\EntityRepository
{
}
