<?php

namespace AppBundle\Repository;

/**
 * CodeBoxAccessByCodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CodeBoxAccessByCodeRepository extends \Doctrine\ORM\EntityRepository
{
}
