<?php

namespace AppBundle\Repository;

/**
 * ImapConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImapConfigRepository extends \Doctrine\ORM\EntityRepository
{
}
