<?php

namespace AppBundle\Repository;

/**
 * MailboxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailboxRepository extends \Doctrine\ORM\EntityRepository
{
}
