<?php

namespace AppBundle\Repository;

/**
 * PeriodExceptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeriodExceptionRepository extends \Doctrine\ORM\EntityRepository
{
}
