<?php

namespace AppBundle\Repository;

/**
 * ReceivedSmsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReceivedSmsRepository extends \Doctrine\ORM\EntityRepository
{
}
